#ifndef DEFINES_H_
#define DEFINES_H_

#define ONLINE false

#define SERVER_SHOW_ONLY_INFO_MESSAGES false
#define SERVER_SHOW_DEBUG_MESSAGES_ON_SCREEN false

#define CLIENT_SHOW_ONLY_INFO_MESSAGES false
#define CLIENT_SHOW_DEBUG_MESSAGES_ON_SCREEN false

#endif  // DEFINES_H_
