#ifndef GAMEOBJECT_MOVABLEOBJECT_ENTITY_PLAYER_PASSIVE_ABILITY_H_
#define GAMEOBJECT_MOVABLEOBJECT_ENTITY_PLAYER_PASSIVE_ABILITY_H_

#include <QImage>

class PassiveAbility {
 public:
  PassiveAbility() = default;

 private:
  QImage image_;
};

#endif  // GAMEOBJECT_MOVABLEOBJECT_ENTITY_PLAYER_PASSIVE_ABILITY_H_
